#!/usr/bin/env python3
"""
masumi-agentagrifinance_agent - Agent Logic
Generated by masumi init and customized for Agrifinance Credit Scoring
"""
import os
import json
import logging
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Initialize Gemini if API key is present
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-2.5-flash')
    logger.info("Successfully configured Gemini API Client.")
else:
    logger.warning("GEMINI_API_KEY not found in environment variables. Falling back to local rules-engine.")
    model = None

def clean_json(text):
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()

def calculate_fallback_score(input_data):
    """Simulated rules-engine fallback scoring logic when Gemini is unavailable."""
    score = 50
    
    farmer_name = input_data.get("farmer_name", "Farmer")
    county = input_data.get("county", "Unknown")
    sub_county = input_data.get("sub_county", "Unknown")
    farm_size = float(input_data.get("farm_size", 1.0))
    primary_crop = input_data.get("primary_crop", "Maize")
    water_source = input_data.get("water_source", "Rain-fed")
    years_farming = int(input_data.get("years_farming", 1))
    ledger_entries_str = input_data.get("ledger_entries", "")
    yield_records_str = input_data.get("yield_records", "")
    
    # Process Ledger Entries (simple text checks)
    total_income = 0
    total_expense = 0
    flagged_count = 0
    
    # Try to parse or scan the entries
    lines = ledger_entries_str.split('\n')
    for line in lines:
        line_lower = line.lower()
        if 'income' in line_lower or 'credit' in line_lower or 'revenue' in line_lower:
            total_income += 5000
        elif 'expense' in line_lower or 'debit' in line_lower or 'cost' in line_lower:
            total_expense += 3000
        if 'flagged' in line_lower or 'non-compliant' in line_lower:
            flagged_count += 1
            
    if total_income > total_expense:
        score += 15
    if flagged_count == 0:
        score += 15
    else:
        score -= flagged_count * 10
        
    if years_farming > 5:
        score += 10
        
    score = max(10, min(95, score))
    risk_level = "Low" if score >= 75 else "Medium" if score >= 45 else "High"
    recommended_loan = int(score * 1500)
    
    strengths = ["Established farming footprint", f"Experienced in {primary_crop} cultivation"]
    if total_income > total_expense:
        strengths.append("Positive farm ledger net cash flow")
        
    vulnerabilities = []
    if water_source.lower() == 'rain-fed':
        vulnerabilities.append("Vulnerable to erratic rainfall patterns")
    if flagged_count > 0:
        vulnerabilities.append(f"{flagged_count} chemical inputs flagged for EU compliance")
        
    result = {
        "credit_score": score,
        "risk_level": risk_level,
        "recommended_loan_cap": recommended_loan,
        "narrative_summary": f"Farmer {farmer_name} manages a {farm_size}-acre farm in {county} County. Based on the ledger analysis, their crop yield history and cash flow indicators point to a {risk_level.lower()} risk profile. Primary irrigation status: {water_source}.",
        "strengths": strengths,
        "vulnerabilities": vulnerabilities
    }
    return result

async def process_job(identifier_from_purchaser: str, input_data: dict):
    """
    Process a credit scoring job
    
    Args:
        identifier_from_purchaser: Identifier from the purchaser
        input_data: Input data matching INPUT_SCHEMA
    
    Returns:
        JSON string or dict of the final credit report
    """
    logger.info(f"Received job from purchaser {identifier_from_purchaser}")
    
    farmer_name = input_data.get("farmer_name", "Farmer")
    county = input_data.get("county", "Unknown")
    sub_county = input_data.get("sub_county", "Unknown")
    farm_size = input_data.get("farm_size", 1.0)
    primary_crop = input_data.get("primary_crop", "Maize")
    water_source = input_data.get("water_source", "Rain-fed")
    years_farming = input_data.get("years_farming", 1)
    ledger_entries = input_data.get("ledger_entries", "No ledger entries recorded.")
    yield_records = input_data.get("yield_records", "No yield records recorded.")
    
    if not model:
        logger.info("Using rules-engine fallback for credit score calculation.")
        return calculate_fallback_score(input_data)
        
    prompt = f"""
    Evaluate agricultural credit risk for farmer {farmer_name}:
    - Location: {county} County, Sub-county: {sub_county}
    - Farm Size: {farm_size} Acres
    - Primary Crop: {primary_crop or 'Maize'}
    - Water Source: {water_source}
    - Years Farming: {years_farming}
    - Historical Farm Ledger: {ledger_entries}
    - Yield Records: {yield_records}
    
    Analyze this data and return a JSON object with exactly these keys:
    - "credit_score": an integer strictly between 0 and 100.
    - "risk_level": "Low" or "Medium" or "High".
    - "recommended_loan_cap": an integer representing recommended maximum loan in KES.
    - "narrative_summary": a 3-sentence summary of their creditworthiness and key risk factors.
    - "strengths": a list of 2-3 key strengths (e.g. stable yield, compliant inputs, positive cash flow).
    - "vulnerabilities": a list of 2-3 key risks (e.g. rain-fed dependence, high fertilizer expense).
    """
    
    try:
        logger.info(f"Invoking Gemini model for {farmer_name}...")
        response = model.generate_content(prompt)
        parsed = json.loads(clean_json(response.text))
        logger.info(f"Successfully generated credit risk report for {farmer_name} with score {parsed.get('credit_score')}")
        return parsed
    except Exception as e:
        logger.error(f"Error in Gemini Credit Report generation: {str(e)}")
        logger.info("Falling back to rules-engine calculation.")
        return calculate_fallback_score(input_data)


