#!/usr/bin/env python3
"""
masumi-agentagrifinance_agent - Main Entry Point
Generated by masumi init

This is the entry point for your Masumi agent.
Run this file to start the agent server.
"""
# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

from masumi import run
from agent import process_job

# Define input schema for the Farmer Credit Scoring Agent
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "farmer_name",
            "type": "string",
            "name": "Farmer Full Name"
        },
        {
            "id": "county",
            "type": "string",
            "name": "County Location"
        },
        {
            "id": "sub_county",
            "type": "string",
            "name": "Sub-County Location"
        },
        {
            "id": "farm_size",
            "type": "number",
            "name": "Farm Size (Acres)"
        },
        {
            "id": "primary_crop",
            "type": "string",
            "name": "Primary Crop"
        },
        {
            "id": "water_source",
            "type": "string",
            "name": "Water Source (e.g. Rain-fed, Irrigated)"
        },
        {
            "id": "years_farming",
            "type": "integer",
            "name": "Years of Farming Experience"
        },
        {
            "id": "ledger_entries",
            "type": "string",
            "name": "Farm Ledger Entries (Format: Date: TYPE KES Amount (Category - Description) [Compliance])"
        },
        {
            "id": "yield_records",
            "type": "string",
            "name": "Crop Yield Records (Format: Season: Crop yielded XX kg, revenue KES YY)"
        }
    ]
}

# Main entry point
if __name__ == "__main__":
    # Config and identifiers loaded from environment variables
    # Default mode is API - use --standalone flag to run standalone
    run(
        start_job_handler=process_job,
        input_schema_handler=INPUT_SCHEMA
        # config, agent_identifier, network loaded from env vars automatically
    )

